# Generated by Django 5.2.12 on 2026-04-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_type', models.CharField(choices=[('cors', 'CORS - Origens Permitidas'), ('allowed_hosts', 'Allowed Hosts - Domínios/IPs Permitidos')], max_length=20, unique=True, verbose_name='Tipo de Configuração')),
                ('value', models.TextField(help_text='Lista de URLs/IPs separados por vírgula. Ex: http://localhost:3000,http://45.71.242.131:3000', verbose_name='Valores')),
                ('is_active', models.BooleanField(default=True, help_text='Se desativado, usa configuração padrão (permite todos)', verbose_name='Ativo')),
                ('description', models.CharField(blank=True, help_text='Descrição opcional desta configuração', max_length=255, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração de Segurança',
                'verbose_name_plural': 'Configurações de Segurança',
                'ordering': ['config_type'],
            },
        ),
    ]
