# Generated by Django 5.2.12 on 2026-03-27 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_type',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='vendor',
            field=models.CharField(choices=[('cisco', 'Cisco'), ('juniper', 'Juniper'), ('huawei', 'Huawei'), ('mikrotik', 'MikroTik'), ('aruba', 'Aruba/HPE'), ('dell', 'Dell'), ('hp', 'HP/Procurve'), ('fortinet', 'Fortinet'), ('paloalto', 'Palo Alto'), ('ubiquiti', 'Ubiquiti'), ('linux', 'Linux'), ('windows', 'Windows'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='password',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='username',
        ),
        migrations.AddField(
            model_name='equipment',
            name='auto_sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='device_type',
            field=models.CharField(choices=[('router', 'Router'), ('switch', 'Switch'), ('firewall', 'Firewall'), ('server', 'Server'), ('ap', 'Access Point'), ('printer', 'Printer'), ('phone', 'IP Phone'), ('camera', 'IP Camera'), ('storage', 'Storage'), ('ups', 'UPS'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='equipment',
            name='enable_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='equipment',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='equipment',
            name='interfaces_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipment',
            name='last_polled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='librenms_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AddField(
            model_name='equipment',
            name='management_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='equipment',
            name='os_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='equipment',
            name='phpipam_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='position',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='equipment',
            name='primary_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='primary_ip_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='rack',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='equipment',
            name='site',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='equipment',
            name='snmp_auth_password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='equipment',
            name='snmp_auth_protocol',
            field=models.CharField(blank=True, choices=[('MD5', 'MD5'), ('SHA', 'SHA')], max_length=10),
        ),
        migrations.AddField(
            model_name='equipment',
            name='snmp_priv_password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='equipment',
            name='snmp_priv_protocol',
            field=models.CharField(blank=True, choices=[('DES', 'DES'), ('AES', 'AES')], max_length=10),
        ),
        migrations.AddField(
            model_name='equipment',
            name='snmp_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='equipment',
            name='snmp_version',
            field=models.CharField(blank=True, choices=[('v1', 'v1'), ('v2c', 'v2c'), ('v3', 'v3')], default='v2c', max_length=5),
        ),
        migrations.AddField(
            model_name='equipment',
            name='ssh_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='equipment',
            name='ssh_port',
            field=models.IntegerField(default=22),
        ),
        migrations.AddField(
            model_name='equipment',
            name='ssh_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='equipment',
            name='sync_status',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='equipment',
            name='uptime',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='equipment',
            name='zabbix_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='hostname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='snmp_community',
            field=models.CharField(blank=True, default='public', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('offline', 'Offline')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='EquipmentInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('if_type', models.CharField(blank=True, max_length=50)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_address_id', models.IntegerField(blank=True, null=True)),
                ('netmask', models.CharField(blank=True, max_length=20)),
                ('speed', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('admin_down', 'Admin Down')], default='down', max_length=20)),
                ('vlan_id', models.IntegerField(blank=True, null=True)),
                ('phpipam_id', models.IntegerField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='equipments.equipment')),
            ],
            options={
                'unique_together': {('equipment', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('partial', 'Partial')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='equipments.equipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='EquipmentType',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
