# Generated by Django 5.2.12 on 2026-04-16 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_remove_equipment_equipment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('online', 'Online'), ('degraded', 'Degraded'), ('offline', 'Offline')], default='offline', max_length=10)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('packet_loss', models.IntegerField(default=0)),
                ('last_check', models.DateTimeField(auto_now=True)),
                ('last_success', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('is_flashing', models.BooleanField(default=False)),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realtime_status', to='equipments.equipment')),
            ],
            options={
                'verbose_name': 'Equipment Real-time Status',
                'verbose_name_plural': 'Equipment Real-time Statuses',
                'ordering': ['-last_check'],
            },
        ),
        migrations.CreateModel(
            name='PingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latency_ms', models.FloatField()),
                ('success', models.BooleanField(default=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ping_history', to='equipments.equipment')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['equipment', 'timestamp'], name='equipments__equipme_2bb407_idx')],
            },
        ),
    ]
